config/routes.rb
Rails.application.routes.draw do
  resources :static_page
  root "static_page#index"
  get "search_photos", to: "static_page#search_photos"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def index
    @photos = []
  end

  def search_photos
    @photos = []
    user_id = params[:user_id]


      flickr = Flickr.new(
        Rails.application.credentials.dig(:flickr, :api_key),
        Rails.application.credentials.dig(:flickr, :secret),
      )

        response = flickr.photos.search(user_id: user_id)
        @photos = response

        render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Flickr Api" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_page/display_images.html.erb
display images

app/views/static_page/index.html.erb
<%= form_with url: search_photos_path, method: :get, local: true do |form| %>
  <%= form.label :user_id, 'Flickr User Id:' %>
  <%= form.text_field :user_id, value: params[:user_id] %>

  <%= form.submit 'Submit' %>
<% end %>

<% if @photos.any? %>
  <h2>Photos:</h2>

  <% @photos.each do |photo| %>
    <%= image_tag "https://live.staticflickr.com/#{photo.server}/#{photo.id}_#{photo.secret}_m.jpg", alt: photo.title %>
    <p><%= photo.title %></p>
  <% end %>

  <% else %>
    <p>No photos found for this user</p>
<% end %>